/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufs.view.cadastros;

import java.awt.Color;
import javax.swing.SwingConstants;

/**
 *
 * @author Ivisson
 */
public class CadastrarEscalaDeTrabalhoView extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarConsultaView
     */
    public CadastrarEscalaDeTrabalhoView() {
        initComponents();
        jButton1.setBackground(new Color(20, 150, 90));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelNomeFuncionario = new javax.swing.JLabel();
        jLabelTelefoneFuncionario = new javax.swing.JLabel();
        jLabelMatriculaFuncionario = new javax.swing.JLabel();
        jLabelDataNascFuncionario = new javax.swing.JLabel();
        jLabelDataNascFuncionario1 = new javax.swing.JLabel();
        jTextFieldCargaHorariaFuncionario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxSegunda = new javax.swing.JCheckBox();
        boxEntradaSegunda = new javax.swing.JComboBox();
        boxSaidaSegunda = new javax.swing.JComboBox();
        jCheckBoxTerca = new javax.swing.JCheckBox();
        boxEntradaTerca = new javax.swing.JComboBox();
        boxSaidaTerca = new javax.swing.JComboBox();
        jCheckBoxQuarta = new javax.swing.JCheckBox();
        boxEntradaQuarta = new javax.swing.JComboBox();
        boxSaidaQuarta = new javax.swing.JComboBox();
        jCheckBoxQuinta = new javax.swing.JCheckBox();
        boxEntradaQuinta = new javax.swing.JComboBox();
        boxSaidaQuinta = new javax.swing.JComboBox();
        jCheckBoxSexta = new javax.swing.JCheckBox();
        boxEntradaSexta = new javax.swing.JComboBox();
        boxSaidaSexta = new javax.swing.JComboBox();
        jCheckBoxSabado = new javax.swing.JCheckBox();
        boxEntradaSabado = new javax.swing.JComboBox();
        boxSaidaSabado = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadatrar Escala de Trabalho");
        setBackground(new java.awt.Color(153, 255, 153));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(20, 150, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 102, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Funcionario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N

        jLabelNomeFuncionario.setText("Aqui aparecerar o nome do Funcionario");

        jLabelTelefoneFuncionario.setText("Aqui aparecerar o Telefone ");

        jLabelMatriculaFuncionario.setText("Aqui aparecerar a Matricula do Funcionario");

        jLabelDataNascFuncionario.setText("Data de nascimento");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMatriculaFuncionario)
                    .addComponent(jLabelDataNascFuncionario))
                .addGap(137, 137, 137))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMatriculaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataNascFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabelDataNascFuncionario1.setText("Carga Horária:");

        jTextFieldCargaHorariaFuncionario.setEditable(false);
        jTextFieldCargaHorariaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCargaHorariaFuncionarioActionPerformed(evt);
            }
        });

        jLabel1.setText("horas.");

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new java.awt.GridLayout(7, 3));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("                  Dia");
        jPanel4.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("                  Entrada");
        jPanel4.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("                    Saída");
        jPanel4.add(jLabel4);

        jCheckBoxSegunda.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBoxSegunda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxSegunda.setText("Segunda-feira.");
        jCheckBoxSegunda.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxSegundaStateChanged(evt);
            }
        });
        jCheckBoxSegunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSegundaActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBoxSegunda);

        boxEntradaSegunda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        boxEntradaSegunda.setEnabled(false);
        jPanel4.add(boxEntradaSegunda);

        boxSaidaSegunda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        boxSaidaSegunda.setEnabled(false);
        jPanel4.add(boxSaidaSegunda);

        jCheckBoxTerca.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBoxTerca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxTerca.setText("Terça-feira.");
        jCheckBoxTerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTercaActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBoxTerca);

        boxEntradaTerca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        boxEntradaTerca.setEnabled(false);
        jPanel4.add(boxEntradaTerca);

        boxSaidaTerca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        boxSaidaTerca.setEnabled(false);
        jPanel4.add(boxSaidaTerca);

        jCheckBoxQuarta.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBoxQuarta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxQuarta.setText("Quarta-feira.");
        jCheckBoxQuarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxQuartaActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBoxQuarta);

        boxEntradaQuarta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        boxEntradaQuarta.setEnabled(false);
        jPanel4.add(boxEntradaQuarta);

        boxSaidaQuarta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        boxSaidaQuarta.setEnabled(false);
        jPanel4.add(boxSaidaQuarta);

        jCheckBoxQuinta.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBoxQuinta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxQuinta.setText("Quinta-feira.");
        jCheckBoxQuinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxQuintaActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBoxQuinta);

        boxEntradaQuinta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        boxEntradaQuinta.setEnabled(false);
        jPanel4.add(boxEntradaQuinta);

        boxSaidaQuinta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        boxSaidaQuinta.setEnabled(false);
        jPanel4.add(boxSaidaQuinta);

        jCheckBoxSexta.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBoxSexta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxSexta.setText("Sexta-feira.");
        jCheckBoxSexta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSextaActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBoxSexta);

        boxEntradaSexta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        boxEntradaSexta.setEnabled(false);
        jPanel4.add(boxEntradaSexta);

        boxSaidaSexta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        boxSaidaSexta.setEnabled(false);
        jPanel4.add(boxSaidaSexta);

        jCheckBoxSabado.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBoxSabado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxSabado.setText("Sábado.");
        jCheckBoxSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSabadoActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBoxSabado);

        boxEntradaSabado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        boxEntradaSabado.setEnabled(false);
        jPanel4.add(boxEntradaSabado);

        boxSaidaSabado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        boxSaidaSabado.setEnabled(false);
        jPanel4.add(boxSaidaSabado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDataNascFuncionario1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCargaHorariaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataNascFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCargaHorariaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldCargaHorariaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCargaHorariaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCargaHorariaFuncionarioActionPerformed

    private void jCheckBoxSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSegundaActionPerformed
        if(boxEntradaSegunda.isEnabled() == false)
            boxEntradaSegunda.setEnabled(true);
        else
            boxEntradaSegunda.setEnabled(false);
        
         if(boxSaidaSegunda.isEnabled() == false)
            boxSaidaSegunda.setEnabled(true);
        else
            boxSaidaSegunda.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxSegundaActionPerformed

    private void jCheckBoxTercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTercaActionPerformed
        if(boxEntradaTerca.isEnabled() == false)
            boxEntradaTerca.setEnabled(true);
        else
            boxEntradaTerca.setEnabled(false);
        
         if(boxSaidaTerca.isEnabled() == false)
            boxSaidaTerca.setEnabled(true);
        else
            boxSaidaTerca.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxTercaActionPerformed

    private void jCheckBoxQuartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxQuartaActionPerformed
        if(boxEntradaQuarta.isEnabled() == false)
            boxEntradaQuarta.setEnabled(true);
        else
            boxEntradaQuarta.setEnabled(false);
        
         if(boxSaidaQuarta.isEnabled() == false)
            boxSaidaQuarta.setEnabled(true);
        else
            boxSaidaQuarta.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxQuartaActionPerformed

    private void jCheckBoxQuintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxQuintaActionPerformed
        if(boxEntradaQuinta.isEnabled() == false)
            boxEntradaQuinta.setEnabled(true);
        else
            boxEntradaQuinta.setEnabled(false);
        
         if(boxSaidaQuinta.isEnabled() == false)
            boxSaidaQuinta.setEnabled(true);
        else
            boxSaidaQuinta.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxQuintaActionPerformed

    private void jCheckBoxSextaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSextaActionPerformed
        if(boxEntradaSexta.isEnabled() == false)
            boxEntradaSexta.setEnabled(true);
        else
            boxEntradaSexta.setEnabled(false);
        
         if(boxSaidaSexta.isEnabled() == false)
            boxSaidaSexta.setEnabled(true);
        else
            boxSaidaSexta.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxSextaActionPerformed

    private void jCheckBoxSegundaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxSegundaStateChanged
        
    }//GEN-LAST:event_jCheckBoxSegundaStateChanged

    private void jCheckBoxSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSabadoActionPerformed
        if(boxEntradaSabado.isEnabled() == false)
            boxEntradaSabado.setEnabled(true);
        else
            boxEntradaSabado.setEnabled(false);
        
         if(boxSaidaSabado.isEnabled() == false)
            boxSaidaSabado.setEnabled(true);
        else
            boxSaidaSabado.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxSabadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarEscalaDeTrabalhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarEscalaDeTrabalhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarEscalaDeTrabalhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarEscalaDeTrabalhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarEscalaDeTrabalhoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxEntradaQuarta;
    private javax.swing.JComboBox boxEntradaQuinta;
    private javax.swing.JComboBox boxEntradaSabado;
    private javax.swing.JComboBox boxEntradaSegunda;
    private javax.swing.JComboBox boxEntradaSexta;
    private javax.swing.JComboBox boxEntradaTerca;
    private javax.swing.JComboBox boxSaidaQuarta;
    private javax.swing.JComboBox boxSaidaQuinta;
    private javax.swing.JComboBox boxSaidaSabado;
    private javax.swing.JComboBox boxSaidaSegunda;
    private javax.swing.JComboBox boxSaidaSexta;
    private javax.swing.JComboBox boxSaidaTerca;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxQuarta;
    private javax.swing.JCheckBox jCheckBoxQuinta;
    private javax.swing.JCheckBox jCheckBoxSabado;
    private javax.swing.JCheckBox jCheckBoxSegunda;
    private javax.swing.JCheckBox jCheckBoxSexta;
    private javax.swing.JCheckBox jCheckBoxTerca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDataNascFuncionario;
    private javax.swing.JLabel jLabelDataNascFuncionario1;
    private javax.swing.JLabel jLabelMatriculaFuncionario;
    private javax.swing.JLabel jLabelNomeFuncionario;
    private javax.swing.JLabel jLabelTelefoneFuncionario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldCargaHorariaFuncionario;
    // End of variables declaration//GEN-END:variables
}
